apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkg-antrea-devtest
  namespace: devtest
spec:
  topology:
    controlPlane:
      count: 1
      class: best-effort-medium
      storageClass: pacificstorage-policy
    workers:
      count: 2
      class: best-effort-medium
      storageClass: pacificstorage-policy
  distribution:
    version: 1.18.5+vmware.1-tkg.1.c40d30d
  settings:
    network:
      cni:
        name: antrea
      services:
        cidrBlocks: ["198.51.100.0/12"]
      pods:
        cidrBlocks: ["192.0.2.0/16"]
